export const items =  [
  {
    id: 1,
    category: 'mobiles',
    title: "Apple iPhone 14",
    imgSrc: 'https://m.media-amazon.com/images/I/71xb2xkN5qL.SL1500.jpg',
    amazonLink: 'https://amzn.to/3PuckZp',
    description: '(512 GB) - Blue',
    detailedDescription: 'The Apple iPhone 14 features a 6.1-inch Super Retina XDR display, A15 Bionic chip, and a 12MP dual-camera system. It comes with 512GB of storage and is available in a stunning blue color.',
    price: '69999',
  },
  {
    id: 2,
    category: 'mobiles',
    title: "Apple iPhone 14 Pro",
    imgSrc: 'https://iplanet.one/cdn/shop/files/iPhone_14_Pro_Deep_Purple_PDP_Image_Position-1a__WWEN.jpg?v=1691140898',
    amazonLink: 'https://amzn.to/3PuckZp',
    description: '(512 GB) - Purple',
    detailedDescription: 'The Apple iPhone 14 Pro offers a 6.1-inch Super Retina XDR display, A16 Bionic chip, and a Pro camera system with 48MP main sensor. It includes 512GB of storage and comes in a sophisticated purple finish.',
    price: '129999',
  },
  {
    id: 3,
    category: 'mobiles',
    title: "Apple iPhone 15",
    imgSrc: 'https://www.imagineonline.store/cdn/shop/files/iPhone_15_Pink_PDP_Image_Position-1__en-IN_823x.jpg?v=1694605258',
    amazonLink: 'https://amzn.to/3PuckZp',
    description: ' (256 GB) - Pink',
    detailedDescription: 'The Apple iPhone 15 features a 6.1-inch Liquid Retina display, A17 Bionic chip, and a 12MP dual-camera system. It comes with 256GB of storage and is available in an elegant pink color.',

    price: '71499',
  },
  {
    id: 4,
    category: 'mobiles',
    title: "Apple iPhone 15 Pro",
    imgSrc: 'https://www.imagineonline.store/cdn/shop/files/iPhone_15_Pro_Max_Black_Titanium_PDP_Image_Position-1__en-IN_ad326452-186a-484a-99a4-82dc80c280fb.jpg?v=1694759404',
    amazonLink: 'https://amzn.to/3PuckZp',
    description: '  (1 TB) - Black',
    detailedDescription: 'The Apple iPhone 15 Pro features a 6.1-inch Super Retina XDR display, A17 Pro chip, and a triple-camera system with advanced computational photography. It offers 1TB of storage and comes in a sleek black finish.',
    price: '129999',
  },
  {
    id: 5,
    category: 'mobiles',
    title: "Apple iPhone SE2",
    imgSrc: 'https://mobilegoo.shop/cdn/shop/products/black1_f58964f4-dbd0-44f9-9ef4-28dde4a9fe22.jpg?v=1673869384',
    amazonLink: 'https://amzn.to/3PuckZp',
    description: ' (256 GB) - Black',
    detailedDescription: 'The Apple iPhone SE2 features a 4.7-inch Retina HD display, A13 Bionic chip, and a 12MP single camera. It includes 256GB of storage and comes in a classic black color.',
    price: '28999',
  },
  {
    id: 6,
    category: 'tablets',
    title: "Apple iPad Mini",
    imgSrc: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/refurb-ipad-mini-wifi-purple-gallery-2022?wid=1144&hei=1144&fmt=jpeg&qlt=90&.v=1674165789066',
    amazonLink: 'https://amzn.to/3PuckZp',
    description: '(512 GB) - Purple',
    detailedDescription: 'The Apple iPad Mini features an 8.3-inch Liquid Retina display, A15 Bionic chip, and a 12MP Ultra Wide front camera. It offers 512GB of storage and comes in a vibrant purple color.',

    price: '49999',
  },
  {
    id: 7,
    category: 'watches',
    title: "Apple Watch Series 9 ",
    imgSrc: 'https://www.reliancedigital.in/medias/Apple-Watch-Series9-494226864-i-1-1200Wx1200H-300Wx300H?context=bWFzdGVyfGltYWdlc3w0NTc2OHxpbWFnZS9qcGVnfGltYWdlcy9oM2UvaGZhLzEwMDUxMTQ0MDI0MDk0LmpwZ3xjZmUyZWY3NjEyMTE3Nzk4MGVlYjk5NmNjMTU1MDA2YzczZjQwYjQwZmMzM2Q4YmZkMGY1NGVhMTFkMTNhZDQ0',
    amazonLink: 'https://amzn.to/3PuckZp',
    description: '41 mm (64gb) - Silver',
    detailedDescription: 'The Apple Watch Series 9 features a 41mm Retina display, S9 SiP chip, and advanced health monitoring capabilities, including ECG and blood oxygen measurements. It offers 64GB of storage and comes in a sleek silver finish.',

    price: '59000',
  },
  {
    id: 8,
    category: 'tablets',
    title: "Apple iPad Air",
    imgSrc: 'https://iplanet.one/cdn/shop/files/iPad_Air_Wi-Fi_Space_Gray_PDP_Image_Position-1a__en-US_032022.jpg?v=1705488812',
    amazonLink: 'https://amzn.to/3PuckZp',
    description: ' (1 TB) - Space Grey',
    detailedDescription: 'The Apple iPad Air features a 10.9-inch Liquid Retina display, M1 chip, and a 12MP Ultra Wide front camera. It offers 1TB of storage and comes in a stylish space grey color.',

    price: '89999',
  },
  {
    id: 9,
    category: 'tablets',
    title: "Apple iPad Pro",
    imgSrc: 'https://media.croma.com/image/upload/v1685967845/Croma%20Assets/Computers%20Peripherals/Tablets%20and%20iPads/Images/264244_ezzssx.png',
    amazonLink: 'https://amzn.to/3PuckZp',
    description: ' (512 GB) - Space Grey',
    detailedDescription: 'The Apple iPad Pro features a 12.9-inch Liquid Retina XDR display, M1 chip, and a pro camera system with LiDAR scanner. It offers 512GB of storage and comes in a sophisticated space grey finish.',
    price: '139999',
  },
  {
    id: 10,
    category: 'laptops',
    title: "Apple Macbook Air 13",
    imgSrc: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT63qqadhZHsIy1rcbfNz6B2ipwo4EDAFTqYKE3ydMOeQ&s',
    amazonLink: 'https://amzn.to/3PuckZp',
    description: '(1TB) - Silver',
    detailedDescription: 'The Apple MacBook Air 13 features a 13.3-inch Retina display, M1 chip, and up to 18 hours of battery life. It includes 1TB of storage and comes in a sleek silver finish.',
price: '69999',
    price: '69999',
  },
  {
    id: 11,
    category: 'laptops',
    title: "Apple Macbook Air 15",
    imgSrc: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ00xj-gzNi2-18PqJpnm-oZaOdBjONDGMY0js0eCpKnw&s',
    amazonLink: 'https://amzn.to/3PuckZp',
    description: '(1TB) - Gold',
    detailedDescription: 'The Apple MacBook Air 15 features a 15-inch Retina display, M2 chip, and up to 18 hours of battery life. It includes 1TB of storage and comes in an elegant gold finish.',
    price: '89999',
  },
  {
    id: 12,
    category: 'laptops',
    title: "Apple Macbook Pro 14",
    imgSrc: 'https://inspireonline.in/cdn/shop/files/r1619_Space_Gray_PDP_Image_Position-1_Avail__en-IN_823x.jpg?v=1691423792',
    description: 'M2 (512 GB) - Black',
     detailedDescription: 'The Apple MacBook Pro 14 features a powerful M2 chip and comes with 512GB of storage. It boasts a stunning 14-inch Retina display, perfect for professional tasks and creative work. With its sleek design and impressive performance.',
    price: '179999',
  },
  {
    id: 13,
    category: 'laptops',
    title: "Apple Macbook Pro 16",
    imgSrc: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcROk4YOAEkX0Q3AlDuekS5RQDnH4tbSCIVt9-5mmB-S4g&s',
    description: 'M2 (1 TB) - Silver',
    detailedDescription: 'The Apple MacBook Pro 16 is equipped with a powerful M2 chip and offers 1TB of storage. Its stunning 16-inch Retina display provides an immersive viewing experience for both work and entertainment. With its advanced features and exceptional performance its the perfect choice for professionals and creatives',
    price: '99999',
  },
  {
    id: 14,
    category: 'laptops',
    title: "Apple Mac mini",
    imgSrc: 'https://media.croma.com/image/upload/v1686893291/Croma%20Assets/Computers%20Peripherals/Desktops/Images/268353_0_tdxbos.png',
    description: 'M2 (512 GB) - Grey',
    detailedDescription: 'The Apple Mac mini is powered by the latest M2 chip and offers 512GB of storage. Its compact design makes it perfect for any workspace, while its powerful performance ensures smooth multitasking and productivity. Whether for work or play, the Mac mini delivers exceptional performance and versatility.',
  
    price: '89999',
  },
  {
    id: 15,
    category: 'laptops',
    title: "Apple Macbook Pro M3",
    imgSrc: 'https://suprememobiles.in/cdn/shop/files/1_0d7d0a5d-fc9b-4273-bc90-8296ad52d26d.png?v=1702477019',
    description: 'M3 (512 GB) - Black',
    detailedDescription: 'The Apple MacBook Pro M3 is powered by the latest M3 chip and offers 512GB of storage. Its sleek design and stunning Retina display make it perfect for both work and entertainment. With its advanced features and exceptional performance, its the ultimate choice for professionals and creatives.',

    price: '159999',
  },
  
  {
    id: 16,
    category: 'watches',
    title: "Apple Watch Ultra ",
    imgSrc: 'https://www.maplestore.in/cdn/shop/files/Apple_Watch_Ultra_LTE_49mm_Titanium_Orange_Alpine_Loop_PDP_Image_Position-1__en-US_3d69d7dc-a3bb-4ef3-9d83-1530dbd0e193_4000x.jpg?v=1701900273',
    description: '43 mm (64gb) - Silver',
    detailedDescription: 'The Apple Watch Ultra is the pinnacle of wearable technology, combining cutting-edge features with sleek design. With its large 43mm display, youll have ample space to view your notifications, track your fitness goals, and stay connected throughout the day. The watch comes with 64GB of storage, allowing you to store your favorite apps, music, and photos right on your wrist. Plus, with LTE connectivity, you can make calls, send messages, and stream music even when youre away from your phone.',
    price: '89000',
  },
  {
    id: 17,
    category: 'watches',
    title: "Apple Watch SE2 ",
    imgSrc: 'https://switch.com.ph/cdn/shop/products/ROSA_Apple_Watch_SE_GPS_40mm_Starlight_Aluminum_Starlight_Sport_Band_PDP_Image_Position-1.jpg?v=1663425525',
    description: '38 mm (32gb) - Beige',
    price: '59000',
    detailedDescription: 'The Apple Watch SE2 features a sleek design and offers advanced health and fitness tracking capabilities. With its 38mm Retina display and 32GB of storage, it provides a seamless experience for staying connected and tracking your activities throughout the day.'
  },
  {
    id: 18,
    category: 'tablets',
    title: "Apple iPad 10th Gen ",
    imgSrc: 'https://www.reliancedigital.in/medias/iPad-10thGen-Wi-Fi-Blue-493178824-i-1-1200Wx1200H?context=bWFzdGVyfGltYWdlc3wzMDIyMzJ8aW1hZ2UvanBlZ3xpbWFnZXMvaDRhL2g4Zi8xMDAxNTUxNjc1Mzk1MC5qcGd8MDI5OGMwZTNiODlkYjIzNTRlNWFkNmM3YzFmM2U5NDZlMTk2ZTA4MjgxNmZiMTdhNTQ3YzBlYmY5Mzc1MWVlZg',
    amazonLink: 'https://amzn.to/3PuckZp',
    description: ' (512gb) - Blue',
    price: '49000',
    detailedDescription: 'The Apple iPad 10th Gen offers a stunning 10.2-inch Retina display and is powered by the powerful A13 Bionic chip. With 512GB of storage, it provides ample space for all your apps, games, and multimedia content. Whether for work or entertainment, the iPad 10th Gen delivers powerful performance and versatility.'
  },
  {
    id: 19,
    category: 'watches',
    title: "Apple Watch 8 ",
    imgSrc: 'https://www.maplestore.in/cdn/shop/files/Apple_Watch_Series_8_LTE_41mm_Midnight_Aluminum_Midnight_Sport_Band_PDP_Image_Position-1__en-US_4d9afa45-fcea-47cf-8065-77f9b68bdd01_4000x.jpg?v=1701887314',
    amazonLink: 'https://amzn.to/3PuckZp',
    description: '38 mm (32gb) - Navy Blue',
    price: '49000',
    detailedDescription: 'The Apple Watch 8 is a stylish and advanced smartwatch that offers a wide range of features. With its 38mm Retina display and 32GB of storage, it provides a seamless experience for staying connected and tracking your fitness activities. Whether for everyday use or workouts, the Apple Watch 8 is the perfect companion for your active lifestyle.'
  },
  {
    id: 20,
    category: 'mobiles',
    title: "Apple iPhone 12",
    imgSrc: 'https://images-cdn.ubuy.co.in/64ce3e40dc164c26877db8d8-walmart-family-mobile-apple-iphone-12.jpg',
    amazonLink: 'https://amzn.to/3PuckZp',
    description: '(128 GB)- Black',
    price: '53000',
    detailedDescription: 'The Apple iPhone 12 features a stunning design and powerful performance. With its 128GB of storage, it provides ample space for all your photos, videos, and apps. Its advanced dual-camera system captures stunning photos and videos, while its 6.1-inch Super Retina XDR display delivers an immersive viewing experience. Whether for work or play, the iPhone 12 is the perfect choice for users seeking a premium smartphone experience.'
  },
  {
    id: 21,
    category: 'watches',
    title: "Apple Watch Ultra 2 ",
    imgSrc: 'https://d3cd3hu9wl72jo.cloudfront.net/2.d/preview/d/d/dd801c10_0ba893c2_MY_Apple_Watch_Ultra_2_LTE_49mm_Titanium_Blue_Alpine_Loop_PDP_Image_Position-1.jpg',
    amazonLink: 'https://amzn.to/3PuckZp',
    description: '49 mm (64gb) - Titanium',
    price: '89000',
    detailedDescription: 'The Apple Watch Ultra 2 is a premium smartwatch that offers advanced features and exceptional performance. With its 49mm Retina display and 64GB of storage, it provides a seamless experience for staying connected and tracking your fitness activities. Its titanium construction ensures durability and style, making it the perfect accessory for users seeking a premium smartwatch experience.'
  },
  {
    id: 22,
    category: 'mobiles',
    title: "Apple iPhone 13",
    imgSrc: 'https://www.aptronixindia.com/media/catalog/product/i/p/iphone_13_green_pdp_image_position-1a_avail__en-in-2_3.jpg',
    amazonLink: 'https://amzn.to/3PuckZp',
    description: '(256 GB) - Green',
    price: '79999',
    detailedDescription: 'The Apple iPhone 13 is the latest addition to the iPhone lineup, featuring a sleek design and powerful performance. With its 6.1-inch Super Retina XDR display and A15 Bionic chip, it delivers stunning visuals and smooth multitasking. The iPhone 13 boasts a dual-camera system with advanced computational photography capabilities, allowing you to capture professional-quality photos and videos. With 256GB of storage, youll have ample space for all your apps, photos, and videos. Whether for work or play, the iPhone 13 offers a premium smartphone experience.'
  },
  {
    id: 23,
    category: 'mobiles',
    title: "Apple iPhone 13 Pro Max",
    imgSrc: 'https://images-cdn.ubuy.co.in/6504c20efa73ad483738c710-pre-owned-apple-iphone-13-pro-max-256gb.jpg',
    amazonLink: 'https://amzn.to/3PuckZp',
    description: '(1 TB) - Graphite',
    price: '149999',
    detailedDescription: 'The Apple iPhone 13 Pro Max is the ultimate flagship smartphone, offering unmatched performance and versatility. With its stunning 6.7-inch Super Retina XDR display and A15 Bionic chip, it delivers unparalleled speed and power. The iPhone 13 Pro Max features a triple-camera system with advanced computational photography capabilities, allowing you to capture breathtaking photos and videos in any lighting conditions. With 1TB of storage, youll have plenty of space for all your apps, photos, and videos. Whether for work or play, the iPhone 13 Pro Max is the perfect choice for users seeking the best-in-class smartphone experience.'
  },
  {
    id: 24,
    category: 'mobiles',
    title: "Apple iPhone SE3",
    imgSrc: 'https://images-cdn.ubuy.co.in/64f3997ec02f48025d6d2288-walmart-family-mobile-apple-iphone-se.jpg',
    amazonLink: 'https://amzn.to/3PuckZp',
    description: '(128 GB) - Red',
    price: '39999',
    detailedDescription: 'The Apple iPhone SE3 combines the power of the latest technology with the classic design of the iPhone SE lineup. With its compact 4.7-inch Retina display and A15 Bionic chip, it delivers impressive performance and efficiency. The iPhone SE3 features a single-camera system with advanced computational photography capabilities, allowing you to capture stunning photos and videos with ease. With 128GB of storage, youll have plenty of space for all your apps, photos, and videos. Whether for everyday use or as a secondary device, the iPhone SE3 offers a premium smartphone experience at an affordable price.'
  },
  {
    id: 25,
    category: 'laptops',
    title: "Apple MacBook Pro 13 M2",
    imgSrc: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR2JJGyRENlgNZdozSwpxDFUIQiXsgJtGLBKAv3o7mTwA&s',
    amazonLink: 'https://amzn.to/3PuckZp',
    description: '(512 GB) - Space Grey',
    price: '169999',
    detailedDescription: 'The Apple MacBook Pro 13 M2 is a powerhouse designed for professionals and creatives. With its stunning 13.3-inch Retina display and M2 pro chip, it delivers exceptional performance and graphics capabilities. The MacBook Pro 13 M2 pro features a Magic Keyboard with Touch Bar and Touch ID, providing convenient and secure access to your device and data. With 512GB of ultra-fast SSD storage, youll have ample space for all your projects, files, and applications. Whether youre editing videos, designing graphics, or developing code, the MacBook Pro 13 M2 pro is the perfect tool to bring your ideas to life.'
  },
  {
    id: 26,
    category: 'laptops',
    title: "Apple MacBook Air M3 ",
    imgSrc: 'https://inventstore.in/wp-content/uploads/2024/03/MacBook_Air_13_in_M3_Space_Grey_PDP_Image_Position_1__en-IN-scaled.webp',
    description: '(256 GB) - Gold',
    price: '99999',
    detailedDescription: 'The Apple MacBook Air M3 combines power, portability, and style in a sleek and lightweight design. With its stunning 13.3-inch Retina display and M5 chip, it delivers impressive performance and efficiency. The MacBook Air M5 features a Magic Keyboard with Touch ID, providing convenient and secure access to your device and data. With 256GB of fast SSD storage, youll have plenty of space for all your files, photos, and apps. Whether youre browsing the web, streaming videos, or tackling work tasks, the MacBook Air M3 is the perfect companion for on-the-go productivity.'
  },
  {
    id: 27,
    category: 'laptops',
    title: "Apple MacBook Pro 16 M2",
    imgSrc: 'https://www.imagineonline.store/cdn/shop/files/r1620_Silver_PDP_Image_Position-1_Avail__en-IN.jpg?v=1692353650',
    amazonLink: 'https://amzn.to/3PuckZp',
    description: '(1 TB) - Silver',
    price: '229999',
    detailedDescription: 'The Apple MacBook Pro 16 M2 max is the ultimate laptop for professionals and power users. With its stunning 16-inch Retina display and M2 max chip, it delivers unrivaled performance and graphics capabilities. The MacBook Pro 16 MM2 max features a Magic Keyboard with Touch Bar and Touch ID, providing convenient and secure access to your device and data. With 1TB of lightning-fast SSD storage, youll have ample space for all your projects, files, and applications. Whether youre editing 4K videos, rendering 3D graphics, or running virtual machines, the MacBook Pro 16 M2 max is the ultimate tool for demanding tasks.'
  },
  
  {
    id: 28,
    category: 'tablets',
    title: "Apple iPad Pro M1",
    imgSrc: 'https://images-cdn.ubuy.co.in/64fbbf138c529f5c9f17a2b9-2021-apple-11-inch-ipad-pro-wi-fi-512gb.jpg',
    amazonLink: 'https://amzn.to/3PuckZp',
    description: '(512 GB) - Space Grey',
    price: '109999',
    detailedDescription: 'The Apple iPad Pro M1 is the ultimate tablet for professionals and creatives. With its stunning 11-inch Liquid Retina display and M1 chip, it delivers desktop-class performance and graphics capabilities. The iPad Pro M1 features ProMotion technology, True Tone, and P3 wide color for an immersive viewing experience. With 512GB of lightning-fast SSD storage, youll have ample space for all your projects, files, and apps. Whether youre editing videos, designing graphics, or multitasking with multiple apps, the iPad Pro M1 is the perfect tool to unleash your creativity.'
  },
  {
    id: 29,
    category: 'tablets',
    title: "Apple iPad 9th Gen",
    imgSrc: 'https://media-ik.croma.com/prod/https://media.croma.com/image/upload/v1700218477/Croma%20Assets/Computers%20Peripherals/Tablets%20and%20iPads/Images/264340_skdoeb.png',
    amazonLink: 'https://amzn.to/3PuckZp',
    description: '(128 GB) - Space Grey',
    price: '36999',
    detailedDescription: 'The Apple iPad 9th Gen combines power, versatility, and affordability in a sleek and portable design. With its stunning 10.2-inch Retina display, it delivers crisp and vibrant visuals for all your entertainment and productivity needs. The iPad 9th Gen features the powerful A13 Bionic chip, providing smooth performance and responsive multitasking. With 128GB of storage, youll have plenty of space for your apps, games, photos, and more. Whether youre browsing the web, streaming videos, or working on documents, the iPad 9th Gen is the perfect companion for everyday use.'
  },
  {
    id: 30,
    category: 'watches',
    title: "Apple Watch SE",
    imgSrc: 'https://www.reliancedigital.in/medias/Apple-SE-Sports-Fitness-Watches-493177922-i-1-1200Wx1200H?context=bWFzdGVyfGltYWdlc3w4ODI0N3xpbWFnZS9qcGVnfGltYWdlcy9oNDkvaGQ5Lzk4OTE5ODMyNjE3MjYuanBnfGRmZmI0ZDlkNmU5NjE3NTRmZjRlZmI2ZDdhMzY1ZTgzODBkMmMxMWE5YTVlNjY0MmYzMzU4ZGQ5OWFjYmY5ZmU',
    amazonLink: 'https://amzn.to/3PuckZp',
    description: '40 mm (32GB) - Space Grey',
    price: '29900',
    detailedDescription: 'The Apple Watch SE combines the essential features of the Apple Watch with an affordable price tag. With its sleek and stylish design, it looks great on your wrist whether youre working out or going out. The Apple Watch SE features a stunning Retina display that provides clear and crisp visuals for all your notifications, messages, and apps. With built-in GPS and water resistance up to 50 meters, you can track your workouts and activities with ease. Plus, with all-day battery life, you can wear it all day and night without needing to recharge.'
  },
  


]